training:
  freq: H
  horizon: 6
  history_window: 48
  model: xgb
  model_params:
    base_model_params:
      n_estimators: 50
      max_depth: 4
  quantiles: [0.1, 0.5, 0.9]
  dataset:
    time_column: timestamp
    target_column: power
    series_id_column: site
    known_covariates: [temp]
  validation:
    method: rolling
    test_size: 24
    step_size: 6
    n_windows: 2
  seed: 7
  timezone: UTC
data:
  path: pv_sample.csv
